// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.discoverystream.enabled", true);
user_pref("app.normandy.user_id", "b9928ca0-7a29-44ec-972d-7aa167234efe");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1570146445);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1570147441);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1570151489);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1570145521);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1570145631);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1570145977);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1570151686);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 24724);
user_pref("browser.cache.disk.capacity", 276480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1570030690);
user_pref("browser.laterrun.bookkeeping.sessionCount", 51);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c6c78aa0-7dee-4663-8b30-72035362adcc}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1570151472145");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1570153265145");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1570151472539");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1570155072539");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190918092025");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1570151979");
user_pref("browser.slowStartup.averageTime", 1383);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190918092025");
user_pref("browser.startup.homepage_override.mstone", "69.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1570151977);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1570030696928");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "27fb3593df2f4909865ea344e7e3d387");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Wed, 02 Oct 2019 21:54:30 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1570146446);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190918092025");
user_pref("extensions.lastAppVersion", "69.0.1");
user_pref("extensions.lastPlatformVersion", "69.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{8ac66b17-868f-4d63-a38c-723521c38052}\",\"addons\":{\"webcompat@mozilla.org\":{\"version\":\"6.1.0\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"6d147359-47b5-4999-b41f-e99ea5fd800f\",\"fxmonitor@mozilla.org\":\"be9ad361-2cbb-4273-bdc8-22510c0f7d43\",\"screenshots@mozilla.org\":\"ef4cff4a-43aa-4491-8af6-a958e708be4d\",\"webcompat-reporter@mozilla.org\":\"41875639-d27c-41ba-a2d3-0fbc6065715f\",\"webcompat@mozilla.org\":\"89f7ea99-4346-4fe8-a364-dd6be144d97a\",\"default-theme@mozilla.org\":\"97d23d42-d05f-4d54-9951-508ca5fd39d1\",\"google@search.mozilla.org\":\"00381062-db2a-41fd-90c5-7683309cde50\",\"amazondotcom@search.mozilla.org\":\"5d20b77e-33f0-42c2-9f2f-760b5b913590\",\"bing@search.mozilla.org\":\"bb0028a3-b0c0-4547-a853-b83e7ec856a8\",\"ddg@search.mozilla.org\":\"36df51d7-b4cd-4acb-8dde-128c19b293fa\",\"ebay@search.mozilla.org\":\"3b12762b-13e2-4da4-a009-b3701dd23004\",\"twitter@search.mozilla.org\":\"9e1fcebc-00de-4d1d-b265-5d77266c62c2\",\"wikipedia@search.mozilla.org\":\"b4f8ac03-9889-45a9-815a-55aa4f45426f\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1570031360);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190918092025");
user_pref("media.gmp-manager.lastCheck", 1570031359);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 65268);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "f9b124c9-6c42-48de-9e1a-8c60c5c3e99b");
user_pref("security.sandbox.plugin.tempDirSuffix", "f08158cb-8b33-423a-b83d-5eae384f7d30");
user_pref("services.blocklist.pinning.checked", 1570058468);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1570060826650\"");
user_pref("services.settings.last_update_seconds", 1570147910);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1570147910);
user_pref("services.settings.main.cfr-fxa.last_check", 1570147910);
user_pref("services.settings.main.cfr.last_check", 1570147910);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1570147910);
user_pref("services.settings.main.hijack-blocklists.last_check", 1570147910);
user_pref("services.settings.main.language-dictionaries.last_check", 1570147910);
user_pref("services.settings.main.normandy-recipes.last_check", 1570147910);
user_pref("services.settings.main.sites-classification.last_check", 1570147910);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1570147910);
user_pref("services.settings.security.onecrl.checked", 1570058468);
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1570151976);
user_pref("toolkit.telemetry.cachedClientID", "84f5235b-9ed3-4fb0-bec3-07a6609f1337");
user_pref("toolkit.telemetry.previousBuildID", "20190918092025");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
